using System.Collections;
using UnityEngine;
using UnityEngine.AI;

namespace StateMachine
{
    [RequireComponent(typeof(NavMeshAgent), typeof(AgentLinkMover))]
    public class EnemyMovement : MonoBehaviour
    {
        public Transform Player;
        public float UpdateRate = 0.1f;
        private NavMeshAgent Agent;
        private AgentLinkMover LinkMover;
        [SerializeField]
        private Animator Animator = null;

        private const string IsWalking = "IsWalking";
        private const string Jump = "Jump";
        private const string Landed = "Landed";

        private Coroutine FollowCoroutine;

        private void Awake()
        {
            Agent = GetComponent<NavMeshAgent>();
            LinkMover = GetComponent<AgentLinkMover>();

            LinkMover.OnLinkStart += HandleLinkStart;
            LinkMover.OnLinkEnd += HandleLinkEnd;
        }

        public void StartChasing()
        {
            if (FollowCoroutine == null)
            {
                FollowCoroutine = StartCoroutine(FollowTarget());
            }
            else
            {
                Debug.LogWarning("Called StartChasing on Enemy that is already chasing! This is likely a bug in some calling class!");
            }
        }

        private IEnumerator FollowTarget()
        {
            WaitForSeconds Wait = new WaitForSeconds(UpdateRate);

            while (gameObject.activeSelf)
            {
                Agent.SetDestination(Player.transform.position);
                yield return Wait;
            }
        }

        private void HandleLinkStart()
        {
            Animator.SetTrigger(Jump);
        }

        private void HandleLinkEnd()
        {
            Animator.SetTrigger(Landed);
        }

        private void Update()
        {
            Animator.SetBool(IsWalking, Agent.velocity.magnitude > 0.01f);
        }
    }
}
